### ISSUE TITLE
NLog.Targets.Syslog stops sending traffic 

### ISSUE THREAD

**Issue by lupusbytes** [luigiberrettini/NLog.Targets.Syslog#193]
I'm not quite sure what causes this.
When running NLog.Targets.Syslog, in production, on a WebAPI, hosted on an IIS, the logger will inevitably stops sending traffic until the WebAPI is restarted.
From what i have noticed, it tends to happen after 24 hours of uptime.

On the actual syslog server, (CentOS), I have tried tcpdumping to sniff if there is any packets incoming from the WebAPI. Nothing ever shows up, after NLog.Targets.Syslog has 'crashed'.
The syslog server still receives logs from unrelated services.

I also added a file target, to tell if it is NLog or the Syslog target, that stops.
The file target continues to log, after the NLog.Targets.Syslog has stopped.

My configuration looks like this.
```
public class NlogConfig
    {
        public static void Register()
        {
            var nlogConfig = new LoggingConfiguration();

            nlogConfig.LoggingRules.Add(new LoggingRule());

            // Layouts
            const string consoleLayout = "${longdate}|${level:uppercase=true}|${logger}|${activityId}|${message}";
            // For syslog, we don't want to prepend the date, as it is already built into the framework
            const string syslogLayout = "${level:uppercase=true}|${logger}|${activityId}|${message}";

            // Targets
            var logconsole = new DebuggerTarget("logconsole")
            {
                Layout = consoleLayout
            };
            var logfile = new FileTarget("logfile")
            {
                Layout = consoleLayout,
                FileName = "${basedir}/api.log"
            };
            var syslog = new SyslogTarget()
            {
                Layout = syslogLayout
            };
            syslog.MessageSend.Udp.Server = "secret";


            // Rules for mapping loggers to targets            
            nlogConfig.AddRule(LogLevel.Trace, LogLevel.Fatal, logconsole);
            nlogConfig.AddRule(LogLevel.Trace, LogLevel.Fatal, syslog);
            nlogConfig.AddRule(LogLevel.Debug, LogLevel.Fatal, logfile);

            // Apply config           
            LogManager.Configuration = nlogConfig;
        }
    }

**Comment by luigiberrettini** [comment]
Thank you @lupusbytes, this issue is strange especially if we consider that UDP code is less complex and more resilient.

I wonder if you were able to reproduce the problem on a local machine.

Maybe turning on the internal logger at the warning level could help to have further details on what happens when the target stops sending packets.

**Comment by luigiberrettini** [comment]
Closing because of inactivity

**Comment by lupusbytes** [comment]
We ended up using a temporary solution of writing to a filetarget, on a network mount, but now we want to get the syslog solution working.

I enabled the internal logger at info level. 
The API I'm mainting writes all HTTP requests and response messages to NLog.
After querying an endpoint that returns 36K worth of data, NLog.Targets.Syslog fails to transmit the data and keeps writing 
```
2021-04-22 17:56:37.2101 Warn [Syslog] SendAsync failed Exception: System.Net.Sockets.SocketException (0x80004005): A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself
   at System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

2021-04-22 17:56:37.7257 Warn [Syslog] SendAsync failed Exception: System.Net.Sockets.SocketException (0x80004005): A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself
   at System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
```
to the internal logger, in an infinite loop.

**Comment by luigiberrettini** [comment]
The maximum length of a message is detailed in many RFCs that are summarized in the [README](https://github.com/luigiberrettini/NLog.Targets.Syslog).

In my opinion Syslog is not suitable for messages that big: you should probably rely on a message broker or on the ELK stack with something like Filebeat to ship logs.

**Comment by lupusbytes** [comment]
I agree, it's not sane to send 1MB through syslog. But doesn't it concern you that it there seems to be an infinite exception loop?
It seems like it's the same message failing to transfer over and over again and blocking future messages.

I did already look at the [README](https://github.com/luigiberrettini/NLog.Targets.Syslog) and its not clear to me what the limit is.
I'm using RFC 5424 with UDP and the MUST NOT exceed is just a dash.
`RFC 5424 (TCP/UDP) | 480 B | 2048 B | -`

I've created a workaround to the issue by checking the size of the response body.
I set the threshold on when to log the body on 10024 bytes like

```
if (body.Length <= 10024)
{
    Logger.Debug(
        "Response: {httpstatus}, body: {body}",
        response.StatusCode,
        Encoding.UTF8.GetString(body));
}
else
{
    Logger.Debug(
        "Response: {httpstatus}, content-type: {content-type}, body size is {size} and too large to log",
        response.StatusCode,
        contentType,
        body.GetHumanReadableSize());
}
```
It seems to work fine with this setting. 
But do you know what the limit is before the socket will start to choke ?
I have an integration with another API that sends large SOAP responses up to 140KB~, and I'm logging those.

**Comment by luigiberrettini** [comment]
> But do you know what the limit is before the socket will start to choke ?

Reading the summary table in the README you can see that, since the IP is used, the maximum safe size is around 64KB.

> I've created a workaround to the issue by checking the size of the response body.

Above the summary table you can find how to configure truncation.

> It seems like it's the same message failing to transfer over and over again and blocking future messages.

This is by design: a logger should not make the application fail, but its primary purpose is not to drop random log entries.
At the moment you can configure throttling but there is no plan to introduce configurable drop and retry policies.
