### ISSUE TITLE
Flush prevents app exit when the server is down

### ISSUE THREAD

**Issue by iangregory** [luigiberrettini/NLog.Targets.Syslog#226]
Minimal steps to reproduce:

- Modify Program.cs in TestAppWithTui to include a call to LogManager.Shutdown() as part of it's exit

```
 public static void Main(string[] args)
        {
            // http://github.com/dotnet/project-system/issues/2239
            Directory.SetCurrentDirectory(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location));

            using (var consoleTest = new ConsoleTest())
            {
                while (true)
                {
                    try
                    {
                        var choice = consoleTest.PromptUserForOperationChoice();
                        if (choice == "Quit")
                        {
                            Trace.WriteLine("Exiting");
                            LogManager.Shutdown();
                            return;
                        }
                        consoleTest.PerformOperation(choice);
                    }
                    catch
                    {
                        Console.WriteLine("Invalid choice");
                    }
                    Console.WriteLine();
                }
            }
        }
```

- Leave test application config pointing at 127.0.0.1 but do not run a syslog server
- Start app and send a single message. Observe repeated `System.Net.Internals.SocketExceptionFactory.ExtendedSocketException` on Console
- Quit app with `Q`. After a few moments a new exception is thrown
```
Unhandled Exception: NLog.NLogRuntimeException: Asynchronous exception has occurred. ---> System.TimeoutException: Timeout.
   --- End of inner exception stack trace ---
   at NLog.Common.AsyncHelpers.RunSynchronously(AsynchronousAction action)
   at NLog.LogFactory.Flush(TimeSpan timeout)
   at NLog.LogFactory.Flush()
   at NLog.LogFactory.set_Configuration(LoggingConfiguration value)
   at NLog.LogFactory.Shutdown()
   at NLog.LogManager.Shutdown()
   at TestAppWithTui.Program.Main(String[] args) in D:\Users\ian\Documents\Projects\Personal\NLog.Targets.Syslog\src\TestAppWithTUI\Program.cs:line 30
```
- The app continues to run with frequent `System.Net.Internals.SocketExceptionFactory.ExtendedSocketException` thrown
- Breaking in the with debugger shows the app waiting for an async operation to complete
![image](https://user-images.githubusercontent.com/1449673/81839421-6482e680-953f-11ea-8e47-8adb0a43c78e.png)

**Comment by snakefoot** [comment]
Created #227 to fix this.

**Comment by snakefoot** [comment]
@iangregory [NLog.Targets.Syslog](https://www.nuget.org/packages/NLog.Targets.Syslog) ver. 6.0.1 has been released. Thanks to @luigiberrettini

**Comment by luigiberrettini** [comment]
Thanks to @snakefoot for the continuous attention to details and the resulting contributions!
