### ISSUE TITLE
Extensions section missing in sample configuration

### ISSUE THREAD

**Issue by RyanGaudion** [luigiberrettini/NLog.Targets.Syslog#294]
**Bug description**
Adding Syslog Target to NLog configuration in .Net 6 Asp.net Application causes the following error:
```
2022-05-19 14:07:06.4123 Warn Error has been raised. Exception: NLog.NLogConfigurationException: Failed to create Target of type: Syslog
 ---> System.ArgumentException: Target symbol-name is unknown: 'Syslog'
   at NLog.Config.Factory`2.CreateInstance(String itemName)
   at NLog.Config.LoggingConfigurationParser.FactoryCreateInstance[T](String classType, INamedItemFactory`2 factory)
   --- End of inner exception stack trace ---
```

Syslog part of my config looks like:

```
 <target xsi:type="Syslog" name="vRealize" layout="${jsonLayoutv0.1}">
      </sl:layout-->
      <sl:messageCreation>
        <sl:rfc>Rfc5424</sl:rfc>
        <sl:rfc5424 hostname="${machinename}" appName="myAPI" procId="${processid}" msgId="${threadid}">
        </sl:rfc5424>
      </sl:messageCreation>
      <sl:messageSend>
        <sl:protocol>TCP</sl:protocol>
        <sl:udp>
          <sl:server>removed</sl:server>
          <sl:port>removed</sl:port>
          <sl:reconnectInterval>3</sl:reconnectInterval>
        </sl:udp>
        <sl:tcp>
          <sl:server>removed</sl:server>
          <sl:port>removed</sl:port>
          <sl:reconnectInterval>3</sl:reconnectInterval>
        </sl:tcp>
      </sl:messageSend>
    </target>
```

I am using NLog v5.0.0, Nlog.Targets.Syslog v6.0.3 and Nlog.Web.AspNetCore v5.0.0

**Comment by snakefoot** [comment]
Created  #295 with better sample-configuration, with explicit NLog-extension-loading.
